<?php

namespace AppBundle\Repository;

/**
 * CitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitesRepository extends \Doctrine\ORM\EntityRepository
{
}
