<?php

namespace AppBundle\Repository;

/**
 * FiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiRepository extends \Doctrine\ORM\EntityRepository
{
}
